import type { ToolDefinition } from "./constants.js";

const GOOGLE_TRANSCRIPTION_LANGUAGES = [
  "af", "sq", "am", "ar", "hy", "az", "eu", "bn", "bs", "bg", "my", "ca", "yue", "zh",
  "hr", "cs", "da", "nl", "en", "et", "fil", "fi", "fr", "gl", "ka", "de", "el", "gu",
  "iw", "hi", "hu", "is", "id", "it", "ja", "jv", "kn", "kk", "km", "ko", "lo", "lv",
  "lt", "mk", "ms", "ml", "mr", "mn", "ne", "no", "fa", "pl", "pt", "pa", "ro", "ru",
  "rw", "sr", "si", "sk", "sl", "ss", "st", "es", "su", "sw", "sv", "ta", "te", "th",
  "tn", "tr", "ts", "uk", "ur", "uz", "ve", "vi", "xh", "zu",
];

const CONVERSATION_RELAY_INTERRUPTIBLE_VALUES = ["none", "any", "speech", "dtmf"];

const CONVERSATION_RELAY_TRANSCRIPTION_ENGINES = [
  "Google", "Telnyx", "Deepgram", "Azure", "xAI", "AssemblyAI", "Speechmatics", "Soniox", "A", "B",
];

export const RCS_CALL_CONTROL_TOOL_DEFINITIONS: Record<string, ToolDefinition> = {
  send_rcs_message: {
    name: "send_rcs_message",
    description: "Send an RCS message from an approved RCS agent.",
    parameters: {
      type: "object",
      properties: {
        agent_id: { type: "string", description: "The RCS agent ID to send from." },
        to: { type: "string", description: "The recipient phone number in E.164 format." },
        messaging_profile_id: { type: "string", description: "The messaging profile associated with the RCS agent." },
        agent_message: { type: "object", description: "The RCS agent message payload, including content_message and optional ttl." },
        mms_fallback: { type: "object", description: "Optional MMS fallback payload." },
        sms_fallback: { type: "object", description: "Optional SMS fallback payload." },
        type: { type: "string", description: "The message type.", enum: ["RCS"] },
        webhook_url: { type: "string", description: "Optional URL to receive message status webhooks." },
      },
      required: ["agent_id", "to", "messaging_profile_id", "agent_message", "type"],
    },
    method: "POST",
    path: "/messages/rcs",
    category: "messaging",
  },
  check_rcs_capabilities: {
    name: "check_rcs_capabilities",
    description: "Check the RCS capabilities available for a recipient.",
    parameters: {
      type: "object",
      properties: {
        agent_id: { type: "string", description: "The RCS agent ID." },
        phone_number: { type: "string", description: "The recipient phone number in E.164 format." },
      },
      required: ["agent_id", "phone_number"],
    },
    method: "GET",
    path: "/messaging/rcs/capabilities/{agent_id}/{phone_number}",
    category: "messaging",
  },
  add_ai_assistant_messages: {
    name: "add_ai_assistant_messages",
    description: "Add messages to the AI assistant conversation on a live call.",
    parameters: {
      type: "object",
      properties: {
        call_control_id: { type: "string", description: "The Call Control ID of the live call." },
        client_state: { type: "string", description: "Optional opaque client state." },
        command_id: { type: "string", description: "Optional command ID for idempotency." },
        messages: { type: "array", items: { type: "object" }, description: "Messages to add to the assistant conversation." },
      },
      required: ["call_control_id"],
    },
    method: "POST",
    path: "/calls/{call_control_id}/actions/ai_assistant_add_messages",
    category: "voice",
  },
  gather_using_ai: {
    name: "gather_using_ai",
    description: "Gather structured information on a live call using a voice assistant.",
    parameters: {
      type: "object",
      properties: {
        call_control_id: { type: "string", description: "The Call Control ID of the live call." },
        parameters: { type: "object", description: "A JSON Schema describing the information to gather." },
        assistant: { type: "object", description: "Optional assistant configuration." },
        client_state: { type: "string", description: "Optional opaque client state." },
        command_id: { type: "string", description: "Optional command ID for idempotency." },
        gather_ended_speech: { type: "string", description: "Speech to play when gathering ends." },
        greeting: { type: "string", description: "Initial greeting spoken by the assistant." },
        interruption_settings: { type: "object", description: "Interruption behavior for the assistant." },
        language: {
          type: "string",
          description: "Language to use for speech recognition.",
          enum: GOOGLE_TRANSCRIPTION_LANGUAGES,
        },
        message_history: { type: "array", items: { type: "object" }, description: "Prior assistant conversation messages." },
        send_message_history_updates: { type: "boolean", description: "Whether to send message history update webhooks." },
        send_partial_results: { type: "boolean", description: "Whether to send partial result webhooks." },
        transcription: { type: "object", description: "Transcription configuration." },
        user_response_timeout_ms: { type: "integer", description: "Time in milliseconds to wait for the user's response." },
        voice: { type: "string", description: "Voice used by the assistant." },
        voice_settings: { type: "object", description: "Voice synthesis settings." },
      },
      required: ["call_control_id", "parameters"],
    },
    method: "POST",
    path: "/calls/{call_control_id}/actions/gather_using_ai",
    category: "voice",
  },
  gather_using_audio: {
    name: "gather_using_audio",
    description: "Play audio and gather DTMF input on a live call.",
    parameters: {
      type: "object",
      properties: {
        call_control_id: { type: "string", description: "The Call Control ID of the live call." },
        audio_url: { type: "string", description: "URL of audio to play while gathering input." },
        client_state: { type: "string", description: "Optional opaque client state." },
        command_id: { type: "string", description: "Optional command ID for idempotency." },
        inter_digit_timeout_millis: { type: "integer", description: "Maximum time between digits in milliseconds." },
        invalid_audio_url: { type: "string", description: "Audio URL to play after invalid input." },
        invalid_media_name: { type: "string", description: "Uploaded media to play after invalid input." },
        maximum_digits: { type: "integer", description: "Maximum number of digits to gather." },
        maximum_tries: { type: "integer", description: "Maximum number of gather attempts." },
        media_name: { type: "string", description: "Uploaded media to play while gathering input." },
        minimum_digits: { type: "integer", description: "Minimum number of digits to gather." },
        terminating_digit: { type: "string", description: "Digit that terminates gathering." },
        timeout_millis: { type: "integer", description: "Overall gather timeout in milliseconds." },
        valid_digits: { type: "string", description: "Digits accepted by the gather action." },
      },
      required: ["call_control_id"],
    },
    method: "POST",
    path: "/calls/{call_control_id}/actions/gather_using_audio",
    category: "voice",
  },
  gather_using_speak: {
    name: "gather_using_speak",
    description: "Speak text and gather DTMF input on a live call.",
    parameters: {
      type: "object",
      properties: {
        call_control_id: { type: "string", description: "The Call Control ID of the live call." },
        payload: { type: "string", description: "Text or SSML to speak while gathering input." },
        voice: { type: "string", description: "Voice used to synthesize the payload." },
        client_state: { type: "string", description: "Optional opaque client state." },
        command_id: { type: "string", description: "Optional command ID for idempotency." },
        inter_digit_timeout_millis: { type: "integer", description: "Maximum time between digits in milliseconds." },
        invalid_payload: { type: "string", description: "Text or SSML to speak after invalid input." },
        language: {
          type: "string",
          description: "Language used for speech synthesis.",
          enum: [
            "arb", "cmn-CN", "cy-GB", "da-DK", "de-DE", "en-AU", "en-GB", "en-GB-WLS",
            "en-IN", "en-US", "es-ES", "es-MX", "es-US", "fr-CA", "fr-FR", "hi-IN",
            "is-IS", "it-IT", "ja-JP", "ko-KR", "nb-NO", "nl-NL", "pl-PL", "pt-BR",
            "pt-PT", "ro-RO", "ru-RU", "sv-SE", "tr-TR",
          ],
        },
        maximum_digits: { type: "integer", description: "Maximum number of digits to gather." },
        maximum_tries: { type: "integer", description: "Maximum number of gather attempts." },
        minimum_digits: { type: "integer", description: "Minimum number of digits to gather." },
        payload_type: { type: "string", description: "Whether the payload is plain text or SSML.", enum: ["text", "ssml"] },
        service_level: { type: "string", description: "Text-to-speech service level.", enum: ["basic", "premium"] },
        terminating_digit: { type: "string", description: "Digit that terminates gathering." },
        timeout_millis: { type: "integer", description: "Overall gather timeout in milliseconds." },
        valid_digits: { type: "string", description: "Digits accepted by the gather action." },
        voice_settings: { type: "object", description: "Voice synthesis settings." },
      },
      required: ["call_control_id", "payload", "voice"],
    },
    method: "POST",
    path: "/calls/{call_control_id}/actions/gather_using_speak",
    category: "voice",
  },
  join_ai_assistant: {
    name: "join_ai_assistant",
    description: "Join a live call to an existing AI assistant conversation.",
    parameters: {
      type: "object",
      properties: {
        call_control_id: { type: "string", description: "The Call Control ID of the live call." },
        conversation_id: { type: "string", description: "The existing AI assistant conversation ID." },
        participant: { type: "object", description: "The participant to add to the conversation." },
        client_state: { type: "string", description: "Optional opaque client state." },
        command_id: { type: "string", description: "Optional command ID for idempotency." },
      },
      required: ["call_control_id", "conversation_id", "participant"],
    },
    method: "POST",
    path: "/calls/{call_control_id}/actions/ai_assistant_join",
    category: "voice",
  },
  start_ai_assistant: {
    name: "start_ai_assistant",
    description: "Start an AI assistant on a live call.",
    parameters: {
      type: "object",
      properties: {
        call_control_id: { type: "string", description: "The Call Control ID of the live call." },
        assistant: { type: "object", description: "Assistant identity or inline assistant configuration." },
        client_state: { type: "string", description: "Optional opaque client state." },
        command_id: { type: "string", description: "Optional command ID for idempotency." },
        greeting: { type: "string", description: "Initial greeting spoken by the assistant." },
        interruption_settings: { type: "object", description: "Interruption behavior for the assistant." },
        message_history: { type: "array", items: { type: "object" }, description: "Prior assistant conversation messages." },
        participants: { type: "array", items: { type: "object" }, description: "Participants in the assistant conversation." },
        send_message_history_updates: { type: "boolean", description: "Whether to send message history update webhooks." },
        transcription: { type: "object", description: "Transcription configuration." },
        voice: { type: "string", description: "Voice used by the assistant." },
        voice_settings: { type: "object", description: "Voice synthesis settings." },
      },
      required: ["call_control_id"],
    },
    method: "POST",
    path: "/calls/{call_control_id}/actions/ai_assistant_start",
    category: "voice",
  },
  stop_ai_assistant: {
    name: "stop_ai_assistant",
    description: "Stop the AI assistant on a live call.",
    parameters: {
      type: "object",
      properties: {
        call_control_id: { type: "string", description: "The Call Control ID of the live call." },
        client_state: { type: "string", description: "Optional opaque client state." },
        command_id: { type: "string", description: "Optional command ID for idempotency." },
      },
      required: ["call_control_id"],
    },
    method: "POST",
    path: "/calls/{call_control_id}/actions/ai_assistant_stop",
    category: "voice",
  },
  start_conversation_relay: {
    name: "start_conversation_relay",
    description: "Start Conversation Relay on a live call.",
    parameters: {
      type: "object",
      properties: {
        call_control_id: { type: "string", description: "The Call Control ID of the live call." },
        assistant: { type: "object", description: "Optional assistant configuration." },
        client_state: { type: "string", description: "Optional opaque client state." },
        command_id: { type: "string", description: "Optional command ID for idempotency." },
        conversation_relay_dtmf_detection: { type: "boolean", description: "Whether Conversation Relay detects DTMF input." },
        conversation_relay_settings: { type: "object", description: "Nested Conversation Relay settings." },
        conversation_relay_url: { type: "string", description: "Conversation Relay WebSocket URL." },
        custom_parameters: { type: "object", description: "Custom parameters sent to the relay connection." },
        dtmf_detection: { type: "boolean", description: "Whether to detect DTMF input." },
        greeting: { type: "string", description: "Initial greeting spoken to the caller." },
        interruptible: {
          type: "string",
          description: "Controls which caller input can interrupt relay speech.",
          enum: CONVERSATION_RELAY_INTERRUPTIBLE_VALUES,
        },
        interruptible_greeting: {
          type: "string",
          description: "Controls which caller input can interrupt the greeting.",
          enum: CONVERSATION_RELAY_INTERRUPTIBLE_VALUES,
        },
        interruption_settings: { type: "object", description: "Interruption behavior for Conversation Relay." },
        language: { type: "string", description: "Default language for text-to-speech and speech recognition." },
        languages: {
          type: "array",
          description: "Per-language text-to-speech and transcription settings.",
          items: {
            type: "object",
            properties: {
              language: { type: "string" },
              speech_model: { type: "string" },
              transcription_engine: { type: "string", enum: CONVERSATION_RELAY_TRANSCRIPTION_ENGINES },
              transcription_engine_config: { type: "object" },
              transcription_provider: { type: "string" },
              tts_provider: { type: "string" },
              voice: { type: "string" },
              voice_settings: { type: "object" },
            },
            required: ["language"],
          },
        },
        provider: { type: "string", description: "Conversation Relay provider." },
        structured_provider: { type: "object", description: "Structured provider configuration." },
        transcription: { type: "object", description: "Transcription configuration." },
        transcription_engine: {
          type: "string",
          description: "Transcription engine to use.",
          enum: CONVERSATION_RELAY_TRANSCRIPTION_ENGINES,
        },
        transcription_engine_config: { type: "object", description: "Transcription engine configuration." },
        tts_provider: { type: "string", description: "Text-to-speech provider." },
        url: { type: "string", description: "WebSocket URL for the relay connection." },
        voice: { type: "string", description: "Voice used for relay speech." },
        voice_settings: { type: "object", description: "Voice synthesis settings." },
      },
      required: ["call_control_id"],
      anyOf: [
        { required: ["url"] },
        { required: ["conversation_relay_url"] },
        { required: ["conversation_relay_settings"] },
      ],
    },
    method: "POST",
    path: "/calls/{call_control_id}/actions/conversation_relay_start",
    category: "voice",
  },
  stop_conversation_relay: {
    name: "stop_conversation_relay",
    description: "Stop Conversation Relay on a live call.",
    parameters: {
      type: "object",
      properties: {
        call_control_id: { type: "string", description: "The Call Control ID of the live call." },
        client_state: { type: "string", description: "Optional opaque client state." },
        command_id: { type: "string", description: "Optional command ID for idempotency." },
      },
      required: ["call_control_id"],
    },
    method: "POST",
    path: "/calls/{call_control_id}/actions/conversation_relay_stop",
    category: "voice",
  },
  switch_supervisor_role: {
    name: "switch_supervisor_role",
    description: "Switch the supervisor role for a bridged live call.",
    parameters: {
      type: "object",
      properties: {
        call_control_id: { type: "string", description: "The Call Control ID of the live call." },
        role: { type: "string", description: "The supervisor role to apply.", enum: ["barge", "whisper", "monitor"] },
      },
      required: ["call_control_id", "role"],
    },
    method: "POST",
    path: "/calls/{call_control_id}/actions/switch_supervisor_role",
    category: "voice",
  },
};
